Be explicit about which test image version - move to CI config
OpenSmalltalk/opensmalltalk-vm pull request #331
Opened 2018-12-31 00:49 UTC by bencoman

First try to see what Travis thinks about these changes.

2019-01-01 22:37 UTC, fniephaus requested changes
LGTM

2019-01-01 22:37 UTC, fniephaus commented on .travis.yml
> +    env: ARCH="macos64x64"    FLAVOR="newspeak.cog.spur"        TESTIMAGE="refer newspeakBootstrap.sh"
I don't really have a better suggestion, so let's go with *refer newspeakBootstrap.sh* for now.

2019-01-01 22:37 UTC, fniephaus commented on .travis.yml
> +    env: ARCH="linux32x86"    FLAVOR="squeak.cog.spur"          TESTIMAGE="Squeak-5.1"
Not that https://github.com/hpi-swa/smalltalkCI/issues/407 is fixed, please update all image names accordingly (`Squeak32-5.1`, ...).

2019-01-01 22:37 UTC, fniephaus commented on tests/smalltalkCI.sh
> +    echo "Skipping SUnit testing for unknown flavor ${FLAVOR}..."
Thanks for cleaning all of this up!

2019-01-11 16:02 UTC, bencoman commented
Hold this for the moment.  I'm developing another idea to demonstrate shortly.

2020-09-10 18:28 UTC, krono commented
@bencoman I think we held for  a moment :)

2025-08-27 08:59 UTC, krono commented
Since we're not using travis anymore, I'm closing

2025-08-27 08:59 UTC, closed without merging