fix event memory leak
OpenSmalltalk/opensmalltalk-vm pull request #373
Opened 2019-02-28 09:56 UTC by maenu

Fixes a memory leak in the macOS event loop, see discussion on mailing list http://lists.squeakfoundation.org/pipermail/vm-dev/2019-February/030595.html

2019-02-28 11:21 UTC, krono commented on platforms/iOS/vm/OSX/sqSqueakOSXApplication+events.m
>         NSMutableArray *alienEventQueue = [[NSMutableArray alloc] init];
@johnmci tries to make sure that everything builds on ARC and non-ARC, so maybe do this:
```suggestion
       NSMutableArray *alienEventQueue = AUTORELEASEOBJ([[NSMutableArray alloc] init]);
```

2019-02-28 11:22 UTC, krono commented on platforms/iOS/vm/OSX/sqSqueakOSXApplication+events.m
> +       }
…and this
```suggestion
       }
       RELEASEOBJ(alienEventQueue)
```

2019-02-28 12:10 UTC, maenu commented
I used `@autoreleasepool` because it is used elsewhere: https://github.com/OpenSmalltalk/opensmalltalk-vm/search?q=autoreleasepool&unscoped_q=autoreleasepool

Having said that, I have virtually no experience with Objective-C and on the coding conventions for the VM, so expert opinions are highly appreciated. Also, we need to make sure that the solution does not have unwanted side-effects. If I am understanding the code correctly, we only have to make sure that `alienEventQueue` is eventually released.

2019-02-28 12:12 UTC, krono commented
the `@autoreleasepool` is ok, leave it there. Just maybe add the other things too :)

2019-02-28 12:21 UTC, maenu commented
I do not fully get the idea of `AUTORELEASEOBJ` and friends, this needs to be tested again. Guille mentioned that `[alienEventQueue release]` lead to segfaults: http://lists.squeakfoundation.org/pipermail/vm-dev/2019-February/030607.html. Not sure if this might cause issues.

2019-02-28 12:24 UTC, krono commented
Yea, don't `release` manually.
The macros get populated depending on availability of ARC: https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/Cog/platforms/iOS/vm/SqueakPureObjc_Prefix.pch

So, when ARC is present (it mostly is nowadays), both macros do exaclty nothing.

2019-02-28 12:47 UTC, maenu commented
Hm, where `@autoreleasepool` is used, `RELEASEOBJ` is mostly not used. Isn't `@autoreleasepool` enough, even for non-ARC?

2019-02-28 12:48 UTC, krono commented
Don't know. That's why I tagged @johnmci

2019-02-28 17:57 UTC, johnmci requested changes
Ok, as @krono pointed out 
NSMutableArray *alienEventQueue = AUTORELEASEOBJ([[NSMutableArray alloc] init]);
with the autoreleasepool. 

I'm not sure anything is build without ARC anymore, but it should be there to be correct for people who need to build on older platforms. 

AUTORELEASEOBJ with ARC does nothing, and the autoreleasepool wrapper then is freeing autorelease objects in the scope of this routine. Since it is pumped from the VM processing requests there isn't a wrapping autorelease pool higher up in the stack.  Easy test is to do invoke the "About Menu"

2019-02-28 17:59 UTC, krono commented
> Ok, as @krono pointed out
> NSMutableArray *alienEventQueue = AUTORELEASEOBJ([[NSMutableArray alloc] init]);
> with the autoreleasepool.

Do we need the `RELEASEOBJ` in this case?

2019-02-28 20:26 UTC, krono commented
John, thank you for clearing up what's going on

BTW: could you open an issue for the autoreleasepool-on-callout?

2019-02-28 20:27 UTC, krono commented on platforms/iOS/vm/OSX/sqSqueakOSXApplication+events.m
> +       }
Ok, this no.

2019-03-11 22:38 UTC, johnmci commented
I will be at Camp Smalltalk at end of March, likely will work on this then.

2019-06-26 18:42 UTC, eliotmiranda commented
@johnmci can you review this now?

2019-06-28 00:06 UTC, merged