Allow choosing an image via zenity when no arguments are provided
OpenSmalltalk/opensmalltalk-vm pull request #408
Opened 2019-06-17 15:04 UTC by MrModder

2019-06-17 17:49 UTC, fniephaus requested changes

2019-06-17 17:49 UTC, fniephaus commented on platforms/unix/config/bin.squeak.sh.in
> +if which zenity &>/dev/null && [ $# -eq 0 ]; then
Could you please swap left and right? No need to check if `zenity` is installed if there are more args anyway.

2019-06-17 17:49 UTC, fniephaus commented on platforms/unix/config/bin.squeak.sh.in
> +  IMAGE=$(zenity --title 'Select an image' --file-selection --filename "${RESOURCES}/" --file-filter '*.image' --file-filter '*')
`IMAGE` is also used for all args (below), so please rename to something like `VM_ARGS`.
Also, `${RESOURCES}` is not defined, maybe remove `--filename "${RESOURCES}/"`?

2019-06-17 17:49 UTC, fniephaus commented on platforms/unix/config/bin.squeak.sh.in
> +echo "Using image: ${IMAGE}"
Please remove this print message.

2019-06-17 17:49 UTC, fniephaus commented on platforms/unix/config/squeak.sh.in
> -LD_LIBRARY_PATH="$PLUGINS:$SVMLLP:${LD_LIBRARY_PATH}" exec $GDB "$BIN/squeak" "$@"
See comments for other file...

2019-06-29 00:50 UTC, eliotmiranda commented
Hi Leon,

    alas I think this way will fail:

if [ $# -eq 0 && which zenity &>/dev/null ]; then
	  VM_ARGS=$(zenity --title 'Select an image' --file-selection --file-filter '*.image' --file-filter '*')
	else
	  VM_ARGS=$@
	fi
	
	LD_LIBRARY_PATH="$PLUGINS:$SVMLLP:${LD_LIBRARY_PATH}" exec $GDB "$BIN/squeak" "${VM_ARGS}"

That's illustrated by the following test programme:
-----------8<-------------
#!/bin/bash
ARGS=$@
echo; echo A
for a in "$ARGS"; do
	echo $a
done
ARGS="$@"
echo; echo B
for a in "$ARGS"; do
	echo $a
done
ARGS="$@"
echo; echo C
for a in $ARGS; do
	echo $a
done
ARGS=$@
echo; echo D
for a in $ARGS; do
	echo $a
done
-----------8<-------------

If one invokes this with ./testshellargs.sh 'arg one' 'arg two' then the output is

A
arg one arg two

B
arg one arg two

C
arg
one
arg
two

D
arg
one
arg
two

We have to find some way of writing this so that the output is
YES!!!
arg one
arg two

2019-06-29 01:05 UTC, eliotmiranda commented
Hi Leon, the only way I know of doing this is to expand $@ within double quotes at the point of command dispatch.  Here's the illustration of the magic incantation:

ZENITY_ARGS=
echo 'YES!!!'
for a in ${ZENITY_ARGS:="$@"}; do
        echo $a
done

so the right form would be

ZENITY_ARGS=
if [ $# -eq 0 && which zenity &>/dev/null ]; then
ZENITY_ARGS=$(zenity --title 'Select an image' --file-selection --file-filter '.image' --file-filter '')
fi

LD_LIBRARY_PATH="$PLUGINS:$SVMLLP:${LD_LIBRARY_PATH}" exec $GDB "$BIN/squeak" ${ZENITY_ARGS:="$@"}

2023-06-05 15:05 UTC, closed without merging