Refixed slip in mvm
OpenSmalltalk/opensmalltalk-vm pull request #646
Opened 2022-07-25 19:02 UTC by KenDickey

Elided 1 line (TARGET_ARCH)

2022-07-26 18:55 UTC, KenDickey commented
More bits & bobs for RV64g.  All tested on riscv64.

2022-07-30 19:27 UTC, eliotmiranda requested changes
Hi Ken,  can you do a different version which doesn't include either of
    src/plugins/SqueakFFIPrims/RiscV64FFIPlugin.c
    src/plugins/ZipPlugin/ZipPlugin.c
?
I generate these carefully. Your generations are against changed VMMaker packages (see the static const char *moduleName = "ZipPlugin * VMMaker.oscog-eem.3218 " INT_EXT; lines).  So I don't want to accept these changes and have to regenerate the plugin files again.  Everything else looks fine.

2022-07-30 20:01 UTC, KenDickey commented
nonRegisterStructReturnIsViaImplicitFirstArgument still needs to return false/0

If you remove VMMaker method
  ThreadedARM64FFIPlugin>>nonRegisterStructReturnIsViaImplicitFirstArgument

The inherited behavior should be correct.

I am not much of a GIT user.  Is current close enough?

2022-08-02 15:07 UTC, eliotmiranda approved these changes

2022-08-02 22:59 UTC, closed without merging